spring.application.name=Spring Boot Expert Course

# Configuração do BD H2
spring.h2.console.settings.web-allow-others=true
spring.datasource.url=jdbc:mysql://localhost:3306/SALES?useTimezone=true&serverTimezone=UTC
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=root
spring.datasource.password=admin123

spring.mvc.pathmatch.matching-strategy=ant-path-matcher

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

#Deixando as consultas que o JPA utiliza visiveis:
spring.jpa.properties.hibernate.show_sql=true
#Se true, formata os sql's quebrando as linhas
#spring.jpa.properties.hibernate.format_sql=true

server.error.include-message=always

security.jwt.expiration=30
security.jwt.subscription.key=dGVzdGUgZGUgc2VndXJhbsOnYQ==

